version: '3.1'

services:
  wordpress:
    image: wordpress:php7.2
    restart: always
    ports:
      - 8002:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_CONFIG_EXTRA: "define( 'WP_MEMORY_LIMIT', '128M' );"
    volumes:
      - ./themes/:/var/www/html/wp-content/themes
      - ./plugins/:/var/www/html/wp-content/plugins
      - uploads:/var/www/html/wp-content/uploads

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
       - db:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]


volumes:
  db:
  uploads: